### ISSUE TITLE
Max 30 Records per Stream

### ISSUE THREAD

**Issue by andyoneal** [acarter24/tap-freshdesk#11]
After running tap-freshdesk, I'm only seeing 30 records in the following streams:
* Agents
* Companies
* Contacts
* Conversations (max 30 per Ticket Detail)

Since default max page size is 30, I'm guessing all of these should be paginated but the tap is only using the first page returned?

**Comment by acarter24** [comment]
Thanks for raising this. In my defense, the API docs are not very clear as to which endpoints support pagination. Some paginate endlessly.

Fix incoming
